version: '3.1'

services:
  mongo:
    image: mongo
    # restart: always
    volumes:
      - ./mongo:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example
    # docker-compose up mongo

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    # docker-compose up mongo-express

  back-install:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - ./backend:/node
    entrypoint: /usr/local/bin/npm install
    # docker-compose up back-install
    # docker-compose run --rm back-install

  back-start:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - ./backend:/node
    ports:
      - 8082:3000
    entrypoint: /usr/local/bin/node ./dist/app.js
    # docker-compose up back-start
    # docker-compose run --rm back-start

  back-install-dev:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - ./backend:/node
    entrypoint: /usr/local/bin/npm --include=dev install
    # docker-compose up back-install-dev
    # docker-compose run --rm back-install-dev

  back-start-dev:
    build: nodemon
    user: 1000:1000
    working_dir: /node
    volumes:
      - ./backend:/node
    ports:
      - 8082:3000
    entrypoint: nodemon ./dist/app.js
    # entrypoint: /usr/local/bin/nodemon ./dist/app.js
    # entrypoint: /usr/local/bin/nodemon ./dist/app.js
    # docker-compose up back-start-dev
    # docker-compose run --rm back-start-dev

  back-bash:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - ./backend:/node
    # docker-compose run --rm back-bash bash

  back-build:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - ./backend:/node
    entrypoint: /usr/local/bin/npx tsc
    # docker-compose up back-build
    # docker-compose run --rm back-bash bash

  front-create:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npx create-react-app frontend --template typescript
    # docker-compose up create
    # docker-compose run --rm create

  front-install:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npm install
    # docker-compose up front-install
    # docker-compose run --rm front-install

  front-start:
    image: node:latest
    user: 1000:1000
    ports: 
    - "8083:3000"
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npm start
    # docker-compose up front-start
    # docker-compose run --rm --service-ports front-start

  front-build:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npx tsc
    # docker-compose up front-build
    # docker-compose run --rm --service-ports front-build

  front-bash:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    # docker-compose run --rm front-bash bash


