version: '3.1'

services:
  front-create:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npx create-react-app frontend --template typescript
    # docker-compose up create
    # docker-compose run --rm create

  front-install:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npm install
    # docker-compose up front-install
    # docker-compose run --rm front-install

  front-start:
    image: node:latest
    user: 1000:1000
    ports: 
    - "8083:3000"
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npm start
    # docker-compose up front-start
    # docker-compose run --rm --service-ports front-start

  front-build:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    entrypoint: /usr/local/bin/npx tsc
    # docker-compose up front-build
    # docker-compose run --rm --service-ports front-build

  front-bash:
    image: node:latest
    user: 1000:1000
    working_dir: /node
    volumes:
      - .:/node
    # docker-compose run --rm front-bash bash


